### ISSUE TITLE
The number of images input is not the same as the number output

### ISSUE THREAD

**Issue by AInseven** [storyicon/comfyui_segment_anything#29] opened 2023-12-08 02:13 UTC
hey,I don't konw why, but increase the thresthold may decrease the output number. Maybe this is a bug, or how can I  avoid this? Thank you.
![image](https://github.com/storyicon/comfyui_segment_anything/assets/57795938/ace211f5-a12d-4a98-927b-06d5b8aea444)

**Comment by norgeous** [comment] 2023-12-08 11:39
I think this issue is a duplicate of https://github.com/storyicon/comfyui_segment_anything/issues/25

Perhaps both are related to a recent merge (30 Nov 2023) https://github.com/storyicon/comfyui_segment_anything/pull/24

A possible temporary workaround is to checkout the commit before #24 was merged:

```sh
cd ComfyUI/custom_nodes/comfyui_segment_anything
git checkout 906a51f9ef2784cde5ff5162d37d95604cfd46f4
```
Please let us know if that works!

Note: Updating ComfyUI will "undo" this workaround

**Comment by AInseven** [comment] 2023-12-08 13:12
Hey, I've tried it, and it works well. Please let me know if your update is relevant to this issue. Thanks.

**Comment by norgeous** [comment] 2023-12-08 13:46
reverted #24 :fist_right: https://github.com/storyicon/comfyui_segment_anything/pull/30

i guess this issue (and duplicate) can be closed now :partying_face:

**Closed** 2023-12-08 16:29 UTC
